### ISSUE TITLE
Can't exclude patches 

### ISSUE THREAD

**Issue by manhduonghn** [ckt1031/revanced-build-script#21]
I try but it said invalid patches. Please fix it

**Comment by manhduonghn** [comment]
Maybe I wrong. So sorry

**Comment by manhduonghn** [comment]
![Screenshot_2023-05-31-12-47-07-524_org adblockplus browser](https://github.com/ckt1031/revanced-build-script/assets/29990924/4494e806-8f20-4a00-b473-8a15b88e25f2)

**Comment by ckt1031** [comment]
The problem should be fixed now

**Comment by manhduonghn** [comment]
Ok thanks, and I want to use your code like [this](https://github.com/manhduonghn/py-revanced), won't I?
