### ISSUE TITLE
What do you think about this

### ISSUE THREAD

**Issue by manhduonghn** [ckt1031/revanced-build-script#22]
`def download_required(self):
        logger.info("Downloading required resources")

        # Build the API urls
        repositories = [
            "revanced/revanced-cli",
            "revanced/revanced-patches",
            "revanced/revanced-integrations",
        ]
        api_urls = [
            f"https://api.github.com/repos/{repo}/releases/latest"
            for repo in repositories
        ]

        downloaded_files = {}

        for api_url, repo in zip(api_urls, repositories):
            try:
                response = self.client.get(api_url)
                response.raise_for_status()

                tools = response.json()

                for tool in tools.get("assets", []):
                    filepath = self._download(tool["browser_download_url"], tool["name"])
                    name = repo.replace("revanced/", "")
                    downloaded_files[name] = filepath

            except requests.exceptions.HTTPError as err:
                logger.error(f"Error downloading resources for {repo}: {err}")
                continue

        return downloaded_files`
It can change to inotia00 resource to build Revanced Extended

**Comment by manhduonghn** [comment]
I think use `patches/app_name/exclude-patches is better python main.py app_name --exclude-patches. How about you?

**Comment by ckt1031** [comment]
Can you show me the example, like the cli command 🤔

**Comment by manhduonghn** [comment]
java -jar "$cli_jar" \
      -m "$integrations_apk" \
      -b "$patches_jar" \
      -a "$base_apk" \
      ${exclude_patches[@]} \
      ${include_patches[@]} \
      --keystore=./src/ks.keystore \
      -o "build/$apk_out.apk"

**Comment by manhduonghn** [comment]
What do you think about this
`exclude_patches_file_path = f"./patches/{args.app_name}/exclude-patches"`
Change for
`parser.add_argument(
        "--exclude-patches",
        help="Exclude patches from build",
        type=str,
        default="none",
    )`

**Comment by manhduonghn** [comment]
So when we need exclude or include patches, we only creat patches/app_name/include-patches and exclude-patches and put them in

**Comment by ckt1031** [comment]
Personally i do not recommend putting the patches information directly in the source code, this script tends to be up to date, so patches are dynamic and subject to change. Giving users to exclude or include the patches with the argument in cli might be a better choice. Even though the official APIs from revanced.app provides the JSON file for that.

**Comment by manhduonghn** [comment]
Thanks a lot. When read your code, I change a small on my code but nice

**Comment by ckt1031** [comment]
Wow, that's a great idea, unfortunately these days I am working on exam, so I will be adding them after June 😅
